set(CMAKE_SYSTEM_NAME Ia16FreeStanding)
set(CMAKE_C_COMPILER ia16-elf-gcc)
set(CMAKE_CXX_COMPILER ia16-elf-g++)
set(CMAKE_ASM_COMPILER ia16-elf-gcc)
set(CMAKE_LINKER ia16-elf-ld)
set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)
set(CMAKE_FIND_ROOT_PATH /opt/ia16-elf-gcc)
set(CMAKE_C_FLAGS "-nostdlib -nodefaultlibs -std=gnu11")
set(CMAKE_CXX_FLAGS "-nostdlib -nodefaultlibs -std=gnu++11")
set(CMAKE_ASM_FLAGS "-nostdlib -nodefaultlibs")
set(CMAKE_EXE_LINKER "-nostdlib -nodefaultlibs -oformat binary")
set(CMAKE_EXECUTABLE_SUFFIX_C ".bin")
