set(CMAKE_SYSTEM_NAME         Ia16FreeStanding)
set(CMAKE_C_COMPILER          ia16-elf-gcc)
set(CMAKE_CXX_COMPILER        ia16-elf-g++)
set(CMAKE_ASM_COMPILER        ia16-elf-gcc)
set(CMAKE_LINKER              ia16-elf-ld)
set(CMAKE_C_COMPILER_WORKS    1)
set(CMAKE_CXX_COMPILER_WORKS  1)
set(CMAKE_FIND_ROOT_PATH      /opt/ia16-elf-gcc)
set(__COMMON_FLAGS__          "-mno-callee-assume-ss-data-segment -mno-callee-assume-ds-data-segment -mcmodel=small -march=i286 -nostdlib -nodefaultlibs")
set(CMAKE_C_FLAGS             "${__COMMON_FLAGS__} -std=gnu11")
set(CMAKE_CXX_FLAGS           "${__COMMON_FLAGS__} -std=gnu++11")
set(CMAKE_ASM_FLAGS           "${__COMMON_FLAGS__} ")
set(CMAKE_EXE_LINKER          "${__COMMON_FLAGS__} -oformat binary")
set(CMAKE_EXECUTABLE_SUFFIX_C ".bin")
set(CMAKE_C_FLAGS_RELEASE     "-Os")
set(CMAKE_CXX_FLAGS_RELEASE   "-Os")