		org 0x0000
		
		include 'variables.asi'
		include '../com/hypercall.asi'
		include 'prologue.asi'
		include '../com/debug.asi'
    include 'bigloop.asi'
		include 'intvectbl.asi'
		include 'optrom.asi'
		include 'msrs.asi'
		include 'lapic.asi'
		include 'synic.asi'
		include 'strings.asi'
		include '../com/buildvars.asi'
		include 'epilogue.asi'