set(CMAKE_HOST_SYSTEM_NAME Linux)
set(CMAKE_HOST_SYSTEM_PROCESSOR x86_64)
set(CMAKE_SYSTEM_NAME DOS)
set(CMAKE_SYSTEM_PROCESSOR I86)

set(WATCOM_DIR /usr/bin/watcom)

set(CMAKE_C_COMPILER ${WATCOM_DIR}/binl64/wcl)
set(CMAKE_C_COMPILER_ID OpenWatcom)
set(CMAKE_C_COMPILER_WORKS 1)

set(CMAKE_CXX_COMPILER ${WATCOM_DIR}/binl64/wcl)
set(CMAKE_CXX_COMPILER_ID OpenWatcom)
set(CMAKE_CXX_COMPILER_WORKS 1)

set(CMAKE_ASM_COMPILER ${WATCOM_DIR}/binl64/wasm)
set(CMAKE_ASM_COMPILER_ID OpenWatcom)
set(CMAKE_ASM_COMPILER_WORKS 1)

set (WATCOM_LIBRARIES ${WATCOM_DIR}/lib286/dos/clibc.lib)
set (EXE2BIN_CMD ${WATCOM_DIR}/binl/exe2bin)

set(CMAKE_C_FLAGS_INIT   "-3 -fp3 -mc -s -zu")
set(CMAKE_CXX_FLAGS_INIT "-3 -fp3 -mc -s -zu")
set(CMAKE_ASM_FLAGS_INIT "-2 -fp3 -mc")
set(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -fo=<OBJECT> <SOURCE>")

set(CMAKE_FIND_ROOT_PATH ${WATCOM_DIR}/lib286;${WATCOM_DIR}/lh;${WATCOM_DIR}/h;${WATCOM_DIR}/binl)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)