function(set_target_stack_size target size)
    # Determine the unit (default is bytes)
    string(REGEX MATCH "([KMGiB]+)$" unit "${size}")
    if(unit STREQUAL "KiB")
        string(REGEX REPLACE "KiB$" "" size "${size}")
        math(EXPR size "${size} * 1024")
    elseif(unit STREQUAL "MiB")
        string(REGEX REPLACE "MiB$" "" size "${size}")
        math(EXPR size "${size} * 1024 * 1024")
    elseif(unit STREQUAL "GiB")
        string(REGEX REPLACE "GiB$" "" size "${size}")
        math(EXPR size "${size} * 1024 * 1024 * 1024")
    endif()

    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        # For GNU ld linker
        target_link_options(${target} PRIVATE "LINKER:-z,stack-size=${size}")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        # For Microsoft linker
        target_link_options(${target} PRIVATE "/STACK:${size}")
    else()
        message(FATAL_ERROR "Unsupported compiler, cannot set stack size")
    endif()
endfunction(set_target_stack_size)